import type { LucideIcon } from "lucide-react";
import {
  BarChart3,
  Users,
  CircleDot,
  Bot,
  Link2,
  Flag,
  Clock,
  CheckCircle2,
  Ban,
  AlertTriangle,
  FileText,
  PenLine,
  BookOpen,
  Clapperboard,
  MessageCircle,
  FileIcon,
  UsersRound,
  Calendar,
  ShoppingCart,
  Briefcase,
  Package,
  DollarSign,
  CreditCard,
  ClipboardList,
  ArrowDownToLine,
  Star,
  Landmark,
  RotateCcw,
  Handshake,
  Settings,
  Wrench,
  ShieldCheck,
  Palette,
  KeyRound,
  Mail,
  Smartphone,
  Image,
  Search,
  BrainCircuit,
  Radio,
  Video,
  Megaphone,
  Store,
  Globe,
  Bell,
  Languages,
  FolderOpen,
  Heart,
  Paintbrush,
  Smile,
  Gift,
  MailOpen,
  Users2,
  CircleDollarSign,
  ListChecks,
  HeartPulse,
  HardDrive,
  Newspaper,
  ScrollText,
  Key,
  KeySquare,
  SpeakerIcon,
  MonitorSmartphone,
  Code,
  MailPlus,
  Send,
  GamepadIcon,
  Tag,
  Star as StarIcon,
  Map,
  Plug,
  Cloud,
  Timer,
  Cog,
  RefreshCw,
  History,
  Scale,
  FileBadge,
  ShieldMinus,
  MessageSquare,
  ListFilter,
  Server,
  Plus,
} from "lucide-react";

export interface AdminNavItem {
  href: string;
  icon: LucideIcon;
}

export interface AdminNavGroup {
  groupKey: string;
  items: AdminNavItem[];
}

export function adminNavItemKey(href: string): string {
  if (href === "/") return "dashboard";
  return href.replace(/^\//, "").replace(/[/-]/g, "_");
}

/** Full admin CP navigation (Sunshine-style sections). */
export const ADMIN_NAV_GROUPS: AdminNavGroup[] = [
  {
    groupKey: "overview",
    items: [{ href: "/", icon: BarChart3 }],
  },
  {
    groupKey: "users",
    items: [
      { href: "/users", icon: Users },
      { href: "/users/banned", icon: Ban },
      { href: "/users/roles", icon: ShieldMinus },
      { href: "/users/send-email", icon: Send },
      { href: "/system/online-users", icon: CircleDot },
      { href: "/system/fake-users", icon: Bot },
      { href: "/system/referrals", icon: Link2 },
    ],
  },
  {
    groupKey: "moderation",
    items: [
      { href: "/moderation/reports", icon: Flag },
      { href: "/moderation/pending-posts", icon: Clock },
      { href: "/moderation/verifications", icon: CheckCircle2 },
      { href: "/moderation/banned-ips", icon: Ban },
      { href: "/moderation/user-reports", icon: AlertTriangle },
      { href: "/moderation/forum-threads", icon: MessageSquare },
      { href: "/moderation/forum-messages", icon: MessageCircle },
    ],
  },
  {
    groupKey: "content",
    items: [
      { href: "/content/posts", icon: FileText },
      { href: "/content/blogs", icon: PenLine },
      { href: "/content/stories", icon: BookOpen },
      { href: "/content/movies", icon: Clapperboard },
      { href: "/content/forums", icon: MessageCircle },
      { href: "/content/forums/sections", icon: FolderOpen },
      { href: "/content/forums/create", icon: Plus },
      { href: "/content/live", icon: Radio },
    ],
  },
  {
    groupKey: "communities",
    items: [
      { href: "/communities/pages", icon: FileIcon },
      { href: "/communities/groups", icon: UsersRound },
      { href: "/communities/events", icon: Calendar },
    ],
  },
  {
    groupKey: "commerce",
    items: [
      { href: "/commerce/products", icon: ShoppingCart },
      { href: "/commerce/jobs", icon: Briefcase },
      { href: "/commerce/orders", icon: Package },
      { href: "/commerce/funding", icon: DollarSign },
    ],
  },
  {
    groupKey: "payments",
    items: [
      { href: "/payments", icon: CreditCard },
      { href: "/payments/transactions", icon: ClipboardList },
      { href: "/payments/withdrawals", icon: ArrowDownToLine },
      { href: "/payments/pro-members", icon: Star },
      { href: "/payments/bank-receipts", icon: Landmark },
      { href: "/payments/refunds", icon: RotateCcw },
      { href: "/payments/requests", icon: ListFilter },
      { href: "/payments/affiliates", icon: Handshake },
      { href: "/payments/settings", icon: Settings },
    ],
  },
  {
    groupKey: "settings",
    items: [
      { href: "/settings/general", icon: Settings },
      { href: "/settings/features", icon: Wrench },
      { href: "/settings/auth", icon: ShieldCheck },
      { href: "/settings/appearance", icon: Palette },
      { href: "/settings/social-login", icon: KeyRound },
      { href: "/settings/email", icon: Mail },
      { href: "/settings/email-security", icon: ShieldCheck },
      { href: "/settings/sms", icon: Smartphone },
      { href: "/settings/media", icon: Image },
      { href: "/settings/storage", icon: HardDrive },
      { href: "/settings/seo", icon: Search },
      { href: "/settings/ai", icon: BrainCircuit },
      { href: "/settings/live", icon: Radio },
      { href: "/settings/video", icon: Video },
      { href: "/settings/ads", icon: Megaphone },
      { href: "/settings/store", icon: Store },
      { href: "/settings/posts", icon: FileText },
      { href: "/settings/website-mode", icon: Globe },
      { href: "/settings/push-notifications", icon: Bell },
      { href: "/settings/pro-features", icon: Star },
      { href: "/settings/pro", icon: Star },
      { href: "/settings/affiliates", icon: Handshake },
      { href: "/settings/custom-code", icon: Code },
      { href: "/settings/third-party", icon: Plug },
    ],
  },
  {
    groupKey: "localization",
    items: [{ href: "/localization/languages", icon: Languages }],
  },
  {
    groupKey: "customization",
    items: [
      { href: "/customization/categories", icon: FolderOpen },
      { href: "/customization/reactions", icon: Heart },
      { href: "/customization/colored-posts", icon: Paintbrush },
      { href: "/customization/stickers", icon: Smile },
      { href: "/customization/gifts", icon: Gift },
      { href: "/customization/email-templates", icon: MailOpen },
      { href: "/customization/custom-pages", icon: FileIcon },
      { href: "/customization/terms-pages", icon: Scale },
      { href: "/customization/genders", icon: Users2 },
      { href: "/customization/currencies", icon: CircleDollarSign },
      { href: "/customization/profile-fields", icon: ListChecks },
      { href: "/customization/groups-fields", icon: ListChecks },
      { href: "/customization/pages-fields", icon: ListChecks },
      { href: "/customization/products-fields", icon: ListChecks },
      { href: "/customization/groups-sub-categories", icon: FolderOpen },
      { href: "/customization/pages-sub-categories", icon: FolderOpen },
      { href: "/customization/products-sub-categories", icon: FolderOpen },
      { href: "/customization/lookups", icon: Tag },
      { href: "/customization/countries", icon: Globe },
    ],
  },
  {
    groupKey: "system",
    items: [
      { href: "/system/node", icon: Server },
      { href: "/system/health", icon: HeartPulse },
      { href: "/system/ffmpeg", icon: Video },
      { href: "/system/verify-apps", icon: ShieldCheck },
      { href: "/system/dlq", icon: AlertTriangle },
      { href: "/system/manage-updates", icon: RefreshCw },
      { href: "/system/changelog", icon: History },
      { href: "/system/backups", icon: HardDrive },
      { href: "/system/upload-storage", icon: Cloud },
      { href: "/system/sitemap", icon: Map },
      { href: "/system/newsletter", icon: Newspaper },
      { href: "/system/announcements", icon: Megaphone },
      { href: "/system/mass-notifications", icon: Bell },
      { href: "/system/activity-log", icon: ScrollText },
      { href: "/system/cronjobs", icon: Timer },
      { href: "/system/auto-settings", icon: Cog },
      { href: "/system/oauth-apps", icon: Key },
      { href: "/system/api-keys", icon: KeySquare },
      { href: "/system/third-party", icon: Plug },
      { href: "/system/games", icon: GamepadIcon },
      { href: "/system/offers", icon: Tag },
      { href: "/system/reviews", icon: StarIcon },
      { href: "/system/user-ads", icon: SpeakerIcon },
      { href: "/system/site-ads", icon: MonitorSmartphone },
      { href: "/system/custom-code", icon: Code },
      { href: "/system/invitations", icon: MailPlus },
      { href: "/system/invitation-keys", icon: FileBadge },
    ],
  },
];
